# Generated by Django 3.2.7 on 2021-09-18 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('author', models.CharField(max_length=64)),
                ('published_date', models.DateField()),
                ('isbn', models.CharField(max_length=13)),
                ('page_count', models.PositiveSmallIntegerField()),
                ('link', models.URLField()),
                ('lang', models.CharField(max_length=2)),
            ],
        ),
    ]
